
export const market = [
  {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849230/minc/donCareJacket_srmt3o.png",
    price: 100,
  },
    {title: `MKI MIYUKI ZOKU AW20 Down jacket`,
    size: "Large",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849236/minc/MMZjacket_wkm3qj.png",
    price: 50,
  },
  {title: `BLOOD ORANGE "The Field" t-shirt`,
    size: "Large",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849230/minc/fieldTop_isruk7.png",
    price: 45,
  },
    {title: `WOMENS ACCESSORIES COLLECTION`,
    size: "Raffle Tickets",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849235/minc/raffle_lzc2po.png",
    price: 2,
  },
    {title: `VAN-DAL Vintage Purse`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849229/minc/vanDal_k1qhmm.png",
    price: 40,
  },
    {title: `VINTAGE PURSE`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849235/minc/vinPurse1_wdrjbh.png",
    price: 35,
  },
    {title: `VINTAGE PURSE`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849234/minc/vinPurse2_ilx9qq.png",
    price: 25,
  },
    {title: `VINTAGE EARRINGS`,
    size: "",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849234/minc/earrings1_pmkiwj.png",
    price: 30,
  },
    {title: `Vintage Pot"`,
    size: "Large",
    image: "https://res.cloudinary.com/daynclfo8/image/upload/v1766849235/minc/pot_whmjwm.png",
    price: 100,
  },
    {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "",
    price: 100,
  },
    {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "",
    price: 100,
  },
    {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "",
    price: 100,
  },
    {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "",
    price: 100,
  },
    {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "",
    price: 100,
  },
    {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "",
    price: 100,
  },
    {title: `DONCARE (AFGK) "Puffer Leather Jacket"`,
    size: "Large",
    image: "",
    price: 100,
  },
  
]
